#!/usr/bin/env bash
# Concatenates all workflow/*.md files into a single workflow_gen.md
# Ordered by filename (00- through 09-).
# Usage: ./agent_bay/workflow/gen_workflow.sh [output_path]
# Default output: agent_bay/workflow/workflow_gen.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${1:-${SCRIPT_DIR}/workflow_gen.md}"

{
  echo "# agent_bay — Generated Workflow"
  echo ""
  echo "> This file is auto-generated by \`workflow/gen_workflow.sh\`. Do not edit directly."
  echo "> Source files are in \`agent_bay/workflow/\`."
  echo ""
  echo "---"
  echo ""

  for f in "${SCRIPT_DIR}"/[0-9][0-9]-*.md; do
    [ -f "$f" ] || continue
    cat "$f"
    echo ""
    echo "---"
    echo ""
  done
} > "$OUTPUT"

echo "Generated: ${OUTPUT}"
