package gogen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type Generator struct {
	SourceDirs []string
	OutputDir  string

	// Internal state
	fset           *token.FileSet
	generatedTypes map[string]bool
	pendingTypes   map[string]bool      // Types we need to resolve from model
	modelTypes     map[string]*typeInfo // Parsed types from models.go
	tsContent      *strings.Builder
}

type typeInfo struct {
	spec      *ast.TypeSpec
	constants []constInfo // For enum types
}

type constInfo struct {
	name  string
	value string
}

func New(sourceDirs []string, outputDir string) *Generator {
	return &Generator{
		SourceDirs: sourceDirs,
		OutputDir:  outputDir,
	}
}

func (g *Generator) Generate() error {
	g.fset = token.NewFileSet()
	g.generatedTypes = make(map[string]bool)
	g.pendingTypes = make(map[string]bool)
	g.modelTypes = make(map[string]*typeInfo)
	g.tsContent = &strings.Builder{}
	g.tsContent.WriteString("// Code generated by gogen. DO NOT EDIT.\n\n")

	// Step 1: Parse models.go to build a lookup of available types
	if err := g.parseModelTypes(); err != nil {
		return err
	}

	// Step 2: Parse API files and generate types, tracking dependencies
	for _, dir := range g.SourceDirs {
		pkgs, err := parser.ParseDir(g.fset, dir, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("failed to parse directory %s: %v", dir, err)
		}

		for _, pkg := range pkgs {
			for _, file := range pkg.Files {
				for _, decl := range file.Decls {
					genDecl, ok := decl.(*ast.GenDecl)
					if !ok || genDecl.Tok != token.TYPE {
						continue
					}

					for _, spec := range genDecl.Specs {
						typeSpec := spec.(*ast.TypeSpec)
						typeName := typeSpec.Name.Name

						// Skip internal types (ending with _)
						if strings.HasSuffix(typeName, "_") {
							continue
						}

						if g.generatedTypes[typeName] {
							continue
						}

						g.generateType(typeName, typeSpec)
					}
				}
			}
		}
	}

	// Step 3: Resolve pending dependencies from model
	if err := g.resolvePendingTypes(); err != nil {
		return err
	}

	outputPath := filepath.Join(g.OutputDir, "models.ts")
	if err := os.MkdirAll(g.OutputDir, 0755); err != nil {
		return err
	}

	return os.WriteFile(outputPath, []byte(g.tsContent.String()), 0644)
}

func (g *Generator) parseModelTypes() error {
	// Find model directory in the parent directory structure
	for _, dir := range g.SourceDirs {
		modelDir := filepath.Join(filepath.Dir(dir), "model")

		if _, err := os.Stat(modelDir); os.IsNotExist(err) {
			continue
		}

		// Parse all .go files in the model directory
		pkgs, err := parser.ParseDir(g.fset, modelDir, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("failed to parse model directory: %v", err)
		}

		for _, pkg := range pkgs {
			for _, file := range pkg.Files {
				// First pass: collect all type declarations
				for _, decl := range file.Decls {
					genDecl, ok := decl.(*ast.GenDecl)
					if !ok {
						continue
					}

					if genDecl.Tok == token.TYPE {
						for _, spec := range genDecl.Specs {
							typeSpec := spec.(*ast.TypeSpec)
							// Skip Params types - they're internal to sqlc
							if strings.HasSuffix(typeSpec.Name.Name, "Params") {
								continue
							}
							g.modelTypes[typeSpec.Name.Name] = &typeInfo{spec: typeSpec}
						}
					}
				}

				// Second pass: collect constants for enum types (skip SQL queries)
				for _, decl := range file.Decls {
					genDecl, ok := decl.(*ast.GenDecl)
					if !ok || genDecl.Tok != token.CONST {
						continue
					}

					var currentType string
					for _, spec := range genDecl.Specs {
						constSpec := spec.(*ast.ValueSpec)

						// Determine the type of this constant
						if constSpec.Type != nil {
							if ident, ok := constSpec.Type.(*ast.Ident); ok {
								currentType = ident.Name
							}
						}

						if currentType == "" {
							continue
						}

						for i, name := range constSpec.Names {
							var value string
							if i < len(constSpec.Values) {
								if lit, ok := constSpec.Values[i].(*ast.BasicLit); ok {
									value = strings.Trim(lit.Value, `"`)
								}
							}

							if info, exists := g.modelTypes[currentType]; exists {
								info.constants = append(info.constants, constInfo{
									name:  name.Name,
									value: value,
								})
							}
						}
					}
				}
			}
		}

		break // Only need to parse one model directory
	}

	return nil
}

func (g *Generator) generateType(typeName string, typeSpec *ast.TypeSpec) {
	if structType, ok := typeSpec.Type.(*ast.StructType); ok {
		g.generatedTypes[typeName] = true
		g.handleStruct(typeName, structType, typeSpec.TypeParams)
	} else {
		// Type alias
		underlyingType := g.goTypeToTS(typeSpec.Type)
		if typeName != underlyingType {
			g.generatedTypes[typeName] = true
			fmt.Fprintf(g.tsContent, "export type %s = %s;\n\n", typeName, underlyingType)
		} else {
			// Same name alias (e.g. type Message = model.Message)
			// Don't mark as generated - let the underlying type be generated directly
			g.pendingTypes[underlyingType] = true
		}
	}
}

func (g *Generator) handleStruct(name string, st *ast.StructType, typeParams *ast.FieldList) {
	tsName := name
	if typeParams != nil && len(typeParams.List) > 0 {
		var params []string
		for _, field := range typeParams.List {
			for _, ident := range field.Names {
				params = append(params, ident.Name)
			}
		}
		tsName = fmt.Sprintf("%s<%s>", name, strings.Join(params, ", "))
	}

	var extends []string
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			// Embedded struct
			embedType := g.goTypeToTS(field.Type)
			if embedType != "any" {
				extends = append(extends, embedType)
			}
		}
	}

	extendsClause := ""
	if len(extends) > 0 {
		extendsClause = " extends " + strings.Join(extends, ", ")
	}

	fmt.Fprintf(g.tsContent, "export interface %s%s {\n", tsName, extendsClause)
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}

		for _, fieldIdent := range field.Names {
			fieldName := fieldIdent.Name
			jsonName := fieldName

			if field.Tag != nil {
				tagValue := strings.Trim(field.Tag.Value, "`")
				if strings.Contains(tagValue, "json:\"") {
					parts := strings.Split(tagValue, "json:\"")
					if len(parts) > 1 {
						jsonPart := strings.Split(parts[1], "\"")[0]
						if jsonPart == "-" {
							continue
						}
						jsonName = strings.Split(jsonPart, ",")[0]
					}
				}
			}

			tsType := g.goTypeToTS(field.Type)
			fmt.Fprintf(g.tsContent, "  %s: %s;\n", jsonName, tsType)
		}
	}
	g.tsContent.WriteString("}\n\n")
}

func (g *Generator) goTypeToTS(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string"
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "byte":
			return "number"
		case "bool":
			return "boolean"
		case "UUID", "NullableUUID":
			return "string"
		default:
			// Check if this is a model type we need to resolve
			if _, exists := g.modelTypes[t.Name]; exists {
				g.pendingTypes[t.Name] = true
			}
			return t.Name
		}
	case *ast.SelectorExpr:
		// Handle things like model.User or pgtype.UUID
		if x, ok := t.X.(*ast.Ident); ok {
			if x.Name == "pgtype" || x.Name == "uuid" {
				return "string"
			}
			// model.SomeType - mark as pending
			typeName := t.Sel.Name
			if _, exists := g.modelTypes[typeName]; exists {
				g.pendingTypes[typeName] = true
			}
			return typeName
		}
		return "any"
	case *ast.StarExpr:
		return g.goTypeToTS(t.X)
	case *ast.ArrayType:
		return g.goTypeToTS(t.Elt) + "[]"
	case *ast.MapType:
		return fmt.Sprintf("{ [key: %s]: %s }", g.goTypeToTS(t.Key), g.goTypeToTS(t.Value))
	default:
		return "any"
	}
}

func (g *Generator) resolvePendingTypes() error {
	// Keep resolving until no more pending types
	for len(g.pendingTypes) > 0 {
		// Get one pending type
		var typeName string
		for t := range g.pendingTypes {
			typeName = t
			break
		}
		delete(g.pendingTypes, typeName)

		if g.generatedTypes[typeName] {
			continue
		}

		info, exists := g.modelTypes[typeName]
		if !exists {
			continue
		}

		g.generatedTypes[typeName] = true

		// Check if it's an enum type (has constants)
		if len(info.constants) > 0 {
			// Generate enum constants
			for _, c := range info.constants {
				fmt.Fprintf(g.tsContent, "export const %s = \"%s\";\n\n", c.name, c.value)
			}
			// Generate type alias for the enum
			fmt.Fprintf(g.tsContent, "export type %s = string;\n\n", typeName)
		} else if structType, ok := info.spec.Type.(*ast.StructType); ok {
			// It's a struct
			g.handleStruct(typeName, structType, info.spec.TypeParams)
		} else {
			// Type alias
			underlyingType := g.goTypeToTS(info.spec.Type)
			if typeName != underlyingType {
				fmt.Fprintf(g.tsContent, "export type %s = %s;\n\n", typeName, underlyingType)
			}
		}
	}

	return nil
}
